# Siioh's PowerItems configuration file

# How to use:

# This set of configurations require integer inputs, they tell the program where to TP the  people who click the items within the directory. This must be in the same world.

# Example:
# Slot 1 X: 1
# Slot 1 Y: 2
# Slot 1 Z: 3
# Slot 1 World: 'asdf'

# This example would sent the player that clicked the first item in the directory to the coordinates 1, 2, 3, in the world “hub”.

Slot 1 X: 0
Slot 1 Y: 0
Slot 1 Z: 0
Slot 1 World: 'asdf'

Slot 2 X: 0
Slot 2 Y: 0
Slot 2 Z: 0
Slot 2 World: 'asdf'

Slot 3 X: 0
Slot 3 Y: 0
Slot 3 Z: 0
Slot 3 World: 'asdf'

Slot 4 X: 0
Slot 4 Y: 0
Slot 4 Z: 0
Slot 4 World: 'asdf'

Slot 5 X: 0
Slot 5 Y: 0
Slot 5 Z: 0
Slot 5 World: 'asdf'

Double Jump: false