name: PowerItems
main: com.gmail.ramsarrantyler.PowerItems
version: 1.1

commands:
   hub:
      description: Teleports you to the hub.
      usage: /<command>
      permissions: PowerItems.hub
      permissions-message: You don’t have the required permission.
   location:
      description: Tells you your pitch and yaw.
      usage: /<command>
      permissions: PowerItems.location
      permissions-message: You don’t have the required permission.
   particle:
      description: Toggles particle effects for the sender.
      usage: /<command>
      permissions: PowerItems.particletoggle
      permissions-message: You don’t have the required permission.
   ender:
      description: Allows you to view your ender chest.
      usage: /<command>
      permission: PowerItems.ender
      permission-message: You don’t have the required permission.
   mod:
      description: Toggles mod mode.
      usage: /<command>
      permission: PowerItems.modtoggle
      permission-message: You don’t have the required permission.
   coord:
      description: Gives the coordinates of the block you are looking at.
      usage: /<command>
      permission: PowerItems.coord
      permission-message: You don't have the required permission.
   pireload:
      description: Reloads PowerItems configuration files.
      usage: /<command>
      permission: PowerItems.reload
      permission-message: You don't have the required permission.
   doublejump:
      description: Toggles double jump for the user.
      usage: /<command>
      permission: PowerItems.doublejumptoggle
      permission-message: You don’t have the required permission.
permissions:
   PowerItems.*:
      description: Access to all permissions of PowerItems.
   PowerItems.lightning:
      description: Able to use the lightning item.
   PowerItems.throwfireball:
      description: The power to throw fireballs like ghasts/dispensers.
   PowerItems.throwtnt:
      description: Throwing TNT, almost like a grenade.
   PowerItems.directory:
      description: Permission to use the compass as the directory for teleportation.
   PowerItems.sniper:
      description: The ability to use the Sniper Bow.
   PowerItems.machine:
      description: The ability to use the Machine Bow.
   PowerItems.wither:
      description: The ability to use the Wither Bow.
   PowerItems.tntbow:
      description: The ability to use the TNT Bow.
   PowerItems.shotbow:
      description: The ability to use the Shot Bow.
   PowerItems.location:
      description: Tells you your pitch and yaw.
   PowerItems.blazeball:
      description: Allows you to shoot fireballs with a blaze rod.
   PowerItems.enderbow:
      description: Shoots an ender pearl from your bow.